# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: '10.0.0.6:5986'
    UserName: 'Cropp-HV.local\administrator'
    UserPassword: 'CroppAdm1!'
    InlineScript: |
      # Write your powershell commands here.
      
      Write-Output "Hello World"


